spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j9_trivia
    username: ironhacker
    password: 1r0nh4ck3r
  main:
    banner-mode: "off"
  jpa:
    show-sql: true
    generate-ddl : true
    hibernate:
      ddl-auto: create
    profiles:
      active: demo-data
